name: mno_navigator
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/iridium
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  dartx: ^1.2.0
  dfunc: ^0.10.0
  equatable: ^2.0.5
  fimber: ^0.7.0
  flutter_bloc: ^8.1.6
  flutter_inappwebview: ^6.1.5
  flutter_spinkit: ^5.2.1
  photo_view: ^0.15.0
  preload_page_view: ^0.2.0
  universal_io: ^2.2.2

  mno_commons:
    path: ../commons
  mno_server:
    path: ../server
  mno_shared:
    path: ../shared
  mno_streamer:
    path: ../streamer

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0

dependency_overrides:
  rxdart: ^0.28.0
  path: ^1.9.1
  meta: ^1.16.0 # mno_shared 0.1.3 requires meta 1.9.1
  collection: ^1.19.1 #universal_io

flutter:
  assets:
    - assets/readium/assets/
    - assets/readium/divina/
    - assets/readium/fonts/
    - assets/readium/readium-css/
    - assets/readium/readium-css/cjk-horizontal/
    - assets/readium/readium-css/cjk-vertical/
    - assets/readium/readium-css/fonts/
    - assets/readium/readium-css/rtl/
    - assets/readium/scripts/
